/* AUTO-GENERATED by scripts/fetch-data.mjs via the "Data refresh" Action.
   Do not edit by hand. Real Data-Hub values that override mi-data.js defaults. */
window.MI_REMOTE = {
  "CREATIVES": [
    {
      "competitor": "Fidelity",
      "color": "var(--c-a)",
      "advertiser": "PTARMIGAN MEDIA LTD",
      "domain": "fidelity.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/9457664785617665584",
      "firstShown": "2026-07-13",
      "lastShown": "2026-07-22",
      "variants": 10,
      "preview": "https://adstransparency.google.com/advertiser/AR09239578838248194049/creative/CR12330893377884127233"
    },
    {
      "competitor": "Fidelity",
      "color": "var(--c-a)",
      "advertiser": "PTARMIGAN MEDIA LTD",
      "domain": "fidelity.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/344913784516717708",
      "firstShown": "2026-01-28",
      "lastShown": "2026-07-22",
      "variants": 115,
      "preview": "https://adstransparency.google.com/advertiser/AR09239578838248194049/creative/CR06921575857496522753"
    },
    {
      "competitor": "Fidelity",
      "color": "var(--c-a)",
      "advertiser": "PTARMIGAN MEDIA LTD",
      "domain": "fidelity.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/17093452660962768042",
      "firstShown": "2026-01-28",
      "lastShown": "2026-07-22",
      "variants": 122,
      "preview": "https://adstransparency.google.com/advertiser/AR09239578838248194049/creative/CR09383356003807920129"
    },
    {
      "competitor": "Fidelity",
      "color": "var(--c-a)",
      "advertiser": "PTARMIGAN MEDIA LTD",
      "domain": "fidelity.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/12674520756769077138",
      "firstShown": "2026-01-28",
      "lastShown": "2026-07-22",
      "variants": 88,
      "preview": "https://adstransparency.google.com/advertiser/AR09239578838248194049/creative/CR14451267879506542593"
    },
    {
      "competitor": "Fidelity",
      "color": "var(--c-a)",
      "advertiser": "PTARMIGAN MEDIA LTD",
      "domain": "fidelity.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/2268875323588579943",
      "firstShown": "2026-01-28",
      "lastShown": "2026-07-22",
      "variants": 62,
      "preview": "https://adstransparency.google.com/advertiser/AR09239578838248194049/creative/CR10286182593560838145"
    },
    {
      "competitor": "Fidelity",
      "color": "var(--c-a)",
      "advertiser": "PTARMIGAN MEDIA LTD",
      "domain": "fidelity.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/5504311993032886278",
      "firstShown": "2026-02-01",
      "lastShown": "2026-07-22",
      "variants": 58,
      "preview": "https://adstransparency.google.com/advertiser/AR09239578838248194049/creative/CR10155775016948465665"
    },
    {
      "competitor": "Perpetual",
      "color": "var(--c-b)",
      "advertiser": "PERPETUAL INVESTMENT MANAGEMENT LIMITED",
      "domain": "perpetual.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/12615938579872536563",
      "firstShown": "2025-10-20",
      "lastShown": "2026-06-30",
      "variants": 114,
      "preview": "https://adstransparency.google.com/advertiser/AR11803797253104074753/creative/CR13735774612015284225"
    },
    {
      "competitor": "Perpetual",
      "color": "var(--c-b)",
      "advertiser": "PERPETUAL INVESTMENT MANAGEMENT LIMITED",
      "domain": "perpetual.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/8713709649065780382",
      "firstShown": "2025-10-20",
      "lastShown": "2026-06-30",
      "variants": 114,
      "preview": "https://adstransparency.google.com/advertiser/AR11803797253104074753/creative/CR16205466844000157697"
    },
    {
      "competitor": "Perpetual",
      "color": "var(--c-b)",
      "advertiser": "PERPETUAL INVESTMENT MANAGEMENT LIMITED",
      "domain": "perpetual.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/10662386818448931913",
      "firstShown": "2025-10-20",
      "lastShown": "2026-06-30",
      "variants": 114,
      "preview": "https://adstransparency.google.com/advertiser/AR11803797253104074753/creative/CR09210400806124126209"
    },
    {
      "competitor": "Perpetual",
      "color": "var(--c-b)",
      "advertiser": "PERPETUAL INVESTMENT MANAGEMENT LIMITED",
      "domain": "perpetual.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/14992816846867867356",
      "firstShown": "2025-10-20",
      "lastShown": "2026-06-30",
      "variants": 114,
      "preview": "https://adstransparency.google.com/advertiser/AR11803797253104074753/creative/CR06918054851897196545"
    },
    {
      "competitor": "Perpetual",
      "color": "var(--c-b)",
      "advertiser": "PERPETUAL INVESTMENT MANAGEMENT LIMITED",
      "domain": "perpetual.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/7214190893279012019",
      "firstShown": "2025-10-20",
      "lastShown": "2026-06-30",
      "variants": 114,
      "preview": "https://adstransparency.google.com/advertiser/AR11803797253104074753/creative/CR02330237031885570049"
    },
    {
      "competitor": "Perpetual",
      "color": "var(--c-b)",
      "advertiser": "PERPETUAL INVESTMENT MANAGEMENT LIMITED",
      "domain": "perpetual.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/17856633093336829550",
      "firstShown": "2025-10-20",
      "lastShown": "2026-06-30",
      "variants": 114,
      "preview": "https://adstransparency.google.com/advertiser/AR11803797253104074753/creative/CR06477410173903175681"
    },
    {
      "competitor": "Vanguard AU",
      "color": "var(--c-c)",
      "advertiser": "Vanguard Investments Australia ltd",
      "domain": "vanguard.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/17698000099960497453",
      "firstShown": "2026-03-18",
      "lastShown": "2026-07-23",
      "variants": 129,
      "preview": "https://adstransparency.google.com/advertiser/AR10426908872051523585/creative/CR14344962216250310657"
    },
    {
      "competitor": "Vanguard AU",
      "color": "var(--c-c)",
      "advertiser": "Vanguard Investments Australia ltd",
      "domain": "vanguard.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/14982647357691852094",
      "firstShown": "2025-03-27",
      "lastShown": "2026-07-23",
      "variants": 484,
      "preview": "https://adstransparency.google.com/advertiser/AR10426908872051523585/creative/CR12908259311725051905"
    },
    {
      "competitor": "Vanguard AU",
      "color": "var(--c-c)",
      "advertiser": "Vanguard Investments Australia ltd",
      "domain": "vanguard.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/17812831187276772440",
      "firstShown": "2025-03-27",
      "lastShown": "2026-07-23",
      "variants": 484,
      "preview": "https://adstransparency.google.com/advertiser/AR10426908872051523585/creative/CR12875608214426615809"
    },
    {
      "competitor": "Vanguard AU",
      "color": "var(--c-c)",
      "advertiser": "Vanguard Investments Australia ltd",
      "domain": "vanguard.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/258695305950578891",
      "firstShown": "2025-03-27",
      "lastShown": "2026-07-23",
      "variants": 484,
      "preview": "https://adstransparency.google.com/advertiser/AR10426908872051523585/creative/CR02062478703249588225"
    },
    {
      "competitor": "Vanguard AU",
      "color": "var(--c-c)",
      "advertiser": "Vanguard Investments Australia ltd",
      "domain": "vanguard.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/12296596504952595577",
      "firstShown": "2024-11-13",
      "lastShown": "2026-07-23",
      "variants": 616,
      "preview": "https://adstransparency.google.com/advertiser/AR10426908872051523585/creative/CR05518069820353937409"
    },
    {
      "competitor": "Vanguard AU",
      "color": "var(--c-c)",
      "advertiser": "Vanguard Investments Australia ltd",
      "domain": "vanguard.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/6167934461486620910",
      "firstShown": "2026-02-05",
      "lastShown": "2026-07-23",
      "variants": 168,
      "preview": "https://adstransparency.google.com/advertiser/AR10426908872051523585/creative/CR09827129548297207809"
    },
    {
      "competitor": "UBS",
      "color": "var(--c-d)",
      "advertiser": "UBS Business Solutions AG",
      "domain": "ubs.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/13833178814837313150",
      "firstShown": "2025-07-31",
      "lastShown": "2026-07-23",
      "variants": 343,
      "preview": "https://adstransparency.google.com/advertiser/AR15402754928304717825/creative/CR14363957147203534849"
    },
    {
      "competitor": "UBS",
      "color": "var(--c-d)",
      "advertiser": "UBS Business Solutions AG",
      "domain": "ubs.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/6957959179657788070",
      "firstShown": "2025-11-04",
      "lastShown": "2026-07-23",
      "variants": 236,
      "preview": "https://adstransparency.google.com/advertiser/AR15402754928304717825/creative/CR14581676461141262337"
    },
    {
      "competitor": "UBS",
      "color": "var(--c-d)",
      "advertiser": "UBS Business Solutions AG",
      "domain": "ubs.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/17470136851421354569",
      "firstShown": "2025-07-31",
      "lastShown": "2026-07-23",
      "variants": 332,
      "preview": "https://adstransparency.google.com/advertiser/AR15402754928304717825/creative/CR13957894858682138625"
    },
    {
      "competitor": "UBS",
      "color": "var(--c-d)",
      "advertiser": "UBS Business Solutions AG",
      "domain": "ubs.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/11898131073845752221",
      "firstShown": "2025-11-04",
      "lastShown": "2026-07-22",
      "variants": 235,
      "preview": "https://adstransparency.google.com/advertiser/AR15402754928304717825/creative/CR11306256636533800961"
    },
    {
      "competitor": "UBS",
      "color": "var(--c-d)",
      "advertiser": "UBS Business Solutions AG",
      "domain": "ubs.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/3117336043057562031",
      "firstShown": "2026-05-15",
      "lastShown": "2026-07-22",
      "variants": 69,
      "preview": "https://adstransparency.google.com/advertiser/AR15402754928304717825/creative/CR11280461750148792321"
    },
    {
      "competitor": "UBS",
      "color": "var(--c-d)",
      "advertiser": "UBS Business Solutions AG",
      "domain": "ubs.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/7421415090917832532",
      "firstShown": "2025-11-04",
      "lastShown": "2026-07-22",
      "variants": 236,
      "preview": "https://adstransparency.google.com/advertiser/AR15402754928304717825/creative/CR01225990082406645761"
    },
    {
      "competitor": "BetaShares",
      "color": "var(--c-us)",
      "advertiser": "BetaShares Capital Ltd",
      "domain": "betashares.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/2326755804232377484",
      "firstShown": "2022-08-11",
      "lastShown": "2026-07-23",
      "variants": 1363,
      "preview": "https://adstransparency.google.com/advertiser/AR10698904349133766657/creative/CR02274410376957263873"
    },
    {
      "competitor": "BetaShares",
      "color": "var(--c-us)",
      "advertiser": "BetaShares Capital Ltd",
      "domain": "betashares.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/3183453430655514417",
      "firstShown": "2026-03-11",
      "lastShown": "2026-07-23",
      "variants": 136,
      "preview": "https://adstransparency.google.com/advertiser/AR10698904349133766657/creative/CR15193720321707343873"
    },
    {
      "competitor": "BetaShares",
      "color": "var(--c-us)",
      "advertiser": "BetaShares Capital Ltd",
      "domain": "betashares.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/13839994351081555897",
      "firstShown": "2023-08-01",
      "lastShown": "2026-07-23",
      "variants": 1084,
      "preview": "https://adstransparency.google.com/advertiser/AR10698904349133766657/creative/CR12815315480705236993"
    },
    {
      "competitor": "BetaShares",
      "color": "var(--c-us)",
      "advertiser": "BetaShares Capital Ltd",
      "domain": "betashares.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/14520443188027788647",
      "firstShown": "2025-11-22",
      "lastShown": "2026-07-23",
      "variants": 238,
      "preview": "https://adstransparency.google.com/advertiser/AR10698904349133766657/creative/CR08369581449497542657"
    },
    {
      "competitor": "BetaShares",
      "color": "var(--c-us)",
      "advertiser": "BetaShares Capital Ltd",
      "domain": "betashares.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/16591517998217628955",
      "firstShown": "2026-06-05",
      "lastShown": "2026-07-23",
      "variants": 48,
      "preview": "https://adstransparency.google.com/advertiser/AR10698904349133766657/creative/CR03348162792346615809"
    },
    {
      "competitor": "BetaShares",
      "color": "var(--c-us)",
      "advertiser": "BetaShares Capital Ltd",
      "domain": "betashares.com.au",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/2927066651444871737",
      "firstShown": "2023-07-07",
      "lastShown": "2026-07-23",
      "variants": 1053,
      "preview": "https://adstransparency.google.com/advertiser/AR10698904349133766657/creative/CR04364707703642128385"
    },
    {
      "competitor": "BlackRock",
      "color": "var(--c-muted)",
      "advertiser": "BlackRock Investment Management (Australia) Limited",
      "domain": "blackrock.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/13934274646460493109",
      "firstShown": "2025-12-08",
      "lastShown": "2026-07-23",
      "variants": 226,
      "preview": "https://adstransparency.google.com/advertiser/AR05832621465492520961/creative/CR09882749512219361281"
    },
    {
      "competitor": "BlackRock",
      "color": "var(--c-muted)",
      "advertiser": "BlackRock, Inc.",
      "domain": "blackrock.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/174542010120974434",
      "firstShown": "2026-05-18",
      "lastShown": "2026-07-23",
      "variants": 67,
      "preview": "https://adstransparency.google.com/advertiser/AR17709583924570619905/creative/CR07510685116687974401"
    },
    {
      "competitor": "BlackRock",
      "color": "var(--c-muted)",
      "advertiser": "BlackRock Investment Management (Australia) Limited",
      "domain": "blackrock.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/14304785982753062153",
      "firstShown": "2025-12-08",
      "lastShown": "2026-07-23",
      "variants": 218,
      "preview": "https://adstransparency.google.com/advertiser/AR05832621465492520961/creative/CR08247133606925828097"
    },
    {
      "competitor": "BlackRock",
      "color": "var(--c-muted)",
      "advertiser": "BlackRock Investment Management (Australia) Limited",
      "domain": "blackrock.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/6263198215117116208",
      "firstShown": "2025-05-22",
      "lastShown": "2026-07-23",
      "variants": 128,
      "preview": "https://adstransparency.google.com/advertiser/AR05832621465492520961/creative/CR14320807251458129921"
    },
    {
      "competitor": "BlackRock",
      "color": "var(--c-muted)",
      "advertiser": "BlackRock, Inc.",
      "domain": "blackrock.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/15919826167389520481",
      "firstShown": "2026-05-18",
      "lastShown": "2026-07-23",
      "variants": 66,
      "preview": "https://adstransparency.google.com/advertiser/AR17709583924570619905/creative/CR08790881689279660033"
    },
    {
      "competitor": "BlackRock",
      "color": "var(--c-muted)",
      "advertiser": "BlackRock Investment Management (Australia) Limited",
      "domain": "blackrock.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/8042587398531170266",
      "firstShown": "2025-05-22",
      "lastShown": "2026-07-23",
      "variants": 206,
      "preview": "https://adstransparency.google.com/advertiser/AR05832621465492520961/creative/CR11462357368935809025"
    },
    {
      "competitor": "Colonial First State",
      "color": "var(--c-a)",
      "advertiser": "The Speed Agency Pty Ltd",
      "domain": "cfs.com.au",
      "format": "Text",
      "image": null,
      "firstShown": "2026-06-25",
      "lastShown": "2026-07-23",
      "variants": 29,
      "preview": "https://adstransparency.google.com/advertiser/AR08855540944452190209/creative/CR04759472278259892225"
    },
    {
      "competitor": "Colonial First State",
      "color": "var(--c-a)",
      "advertiser": "The Speed Agency Pty Ltd",
      "domain": "cfs.com.au",
      "format": "Text",
      "image": null,
      "firstShown": "2026-06-26",
      "lastShown": "2026-07-23",
      "variants": 28,
      "preview": "https://adstransparency.google.com/advertiser/AR08855540944452190209/creative/CR10496151106436988929"
    },
    {
      "competitor": "Colonial First State",
      "color": "var(--c-a)",
      "advertiser": "The Speed Agency Pty Ltd",
      "domain": "cfs.com.au",
      "format": "Text",
      "image": null,
      "firstShown": "2026-06-24",
      "lastShown": "2026-07-23",
      "variants": 29,
      "preview": "https://adstransparency.google.com/advertiser/AR08855540944452190209/creative/CR12813157457207492609"
    },
    {
      "competitor": "Colonial First State",
      "color": "var(--c-a)",
      "advertiser": "The Speed Agency Pty Ltd",
      "domain": "cfs.com.au",
      "format": "Text",
      "image": null,
      "firstShown": "2026-06-23",
      "lastShown": "2026-07-22",
      "variants": 30,
      "preview": "https://adstransparency.google.com/advertiser/AR08855540944452190209/creative/CR15236146833290952705"
    },
    {
      "competitor": "Colonial First State",
      "color": "var(--c-a)",
      "advertiser": "The Speed Agency Pty Ltd",
      "domain": "cfs.com.au",
      "format": "Text",
      "image": null,
      "firstShown": "2026-06-23",
      "lastShown": "2026-07-22",
      "variants": 30,
      "preview": "https://adstransparency.google.com/advertiser/AR08855540944452190209/creative/CR01380446546708922369"
    },
    {
      "competitor": "Resolution Capital",
      "color": "var(--c-b)",
      "advertiser": "Pinnacle Investment Management Group Limited",
      "domain": "rescap.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/2226425401641257740",
      "firstShown": "2024-06-28",
      "lastShown": "2026-07-23",
      "variants": 754,
      "preview": "https://adstransparency.google.com/advertiser/AR09429417629681975297/creative/CR05173237083820523521"
    },
    {
      "competitor": "Resolution Capital",
      "color": "var(--c-b)",
      "advertiser": "Pinnacle Investment Management Group Limited",
      "domain": "rescap.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/13623948315611592531",
      "firstShown": "2024-06-28",
      "lastShown": "2026-07-23",
      "variants": 755,
      "preview": "https://adstransparency.google.com/advertiser/AR09429417629681975297/creative/CR10510613970719604737"
    },
    {
      "competitor": "Resolution Capital",
      "color": "var(--c-b)",
      "advertiser": "Pinnacle Investment Management Group Limited",
      "domain": "rescap.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/10960129305928772198",
      "firstShown": "2026-04-12",
      "lastShown": "2026-07-22",
      "variants": 102,
      "preview": "https://adstransparency.google.com/advertiser/AR09429417629681975297/creative/CR11453110570635493377"
    },
    {
      "competitor": "Resolution Capital",
      "color": "var(--c-b)",
      "advertiser": "Pinnacle Investment Management Group Limited",
      "domain": "rescap.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/10452347193741089825",
      "firstShown": "2026-01-09",
      "lastShown": "2026-07-21",
      "variants": 193,
      "preview": "https://adstransparency.google.com/advertiser/AR09429417629681975297/creative/CR12853557568861110273"
    },
    {
      "competitor": "Resolution Capital",
      "color": "var(--c-b)",
      "advertiser": "Pinnacle Investment Management Group Limited",
      "domain": "rescap.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/10106471113836913548",
      "firstShown": "2026-01-12",
      "lastShown": "2026-04-10",
      "variants": 90,
      "preview": "https://adstransparency.google.com/advertiser/AR09429417629681975297/creative/CR07780762762023534593"
    },
    {
      "competitor": "Resolution Capital",
      "color": "var(--c-b)",
      "advertiser": "Pinnacle Investment Management Group Limited",
      "domain": "rescap.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/3966947437024653995",
      "firstShown": "2024-06-29",
      "lastShown": "2025-11-08",
      "variants": 269,
      "preview": "https://adstransparency.google.com/advertiser/AR09429417629681975297/creative/CR16385524500252327937"
    },
    {
      "competitor": "Robeco",
      "color": "var(--c-c)",
      "advertiser": "Robeco Nederland B.V.",
      "domain": "robeco.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/12720321361888095066",
      "firstShown": "2025-02-14",
      "lastShown": "2026-07-23",
      "variants": 438,
      "preview": "https://adstransparency.google.com/advertiser/AR01652962350489141249/creative/CR00208453849709543425"
    },
    {
      "competitor": "Robeco",
      "color": "var(--c-c)",
      "advertiser": "Robeco Nederland B.V.",
      "domain": "robeco.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/6144541679797828306",
      "firstShown": "2025-01-31",
      "lastShown": "2026-07-22",
      "variants": 435,
      "preview": "https://adstransparency.google.com/advertiser/AR01652962350489141249/creative/CR17048919977651863553"
    },
    {
      "competitor": "Robeco",
      "color": "var(--c-c)",
      "advertiser": "Robeco Nederland B.V.",
      "domain": "robeco.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/6699872085608535748",
      "firstShown": "2025-09-24",
      "lastShown": "2025-12-31",
      "variants": 99,
      "preview": "https://adstransparency.google.com/advertiser/AR01652962350489141249/creative/CR10963027975796162561"
    },
    {
      "competitor": "Robeco",
      "color": "var(--c-c)",
      "advertiser": "Robeco Nederland B.V.",
      "domain": "robeco.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/3908717235931946050",
      "firstShown": "2025-06-03",
      "lastShown": "2025-12-31",
      "variants": 210,
      "preview": "https://adstransparency.google.com/advertiser/AR01652962350489141249/creative/CR07449812691230654465"
    },
    {
      "competitor": "Robeco",
      "color": "var(--c-c)",
      "advertiser": "Robeco Nederland B.V.",
      "domain": "robeco.com",
      "format": "Image",
      "image": "https://tpc.googlesyndication.com/archive/simgad/5250462927076374520",
      "firstShown": "2025-02-15",
      "lastShown": "2025-09-24",
      "variants": 221,
      "preview": "https://adstransparency.google.com/advertiser/AR01652962350489141249/creative/CR05697734624537477121"
    }
  ],
  "AD_SOV": {
    "q1": [
      {
        "name": "BetaShares",
        "v": 35,
        "color": "var(--c-us)"
      },
      {
        "name": "BlackRock",
        "v": 29,
        "color": "var(--c-muted)"
      },
      {
        "name": "Vanguard AU",
        "v": 27,
        "color": "var(--c-c)"
      },
      {
        "name": "UBS",
        "v": 14,
        "color": "var(--c-d)"
      },
      {
        "name": "Perpetual",
        "v": 12,
        "color": "var(--c-b)"
      },
      {
        "name": "Fidelity",
        "v": 8,
        "color": "var(--c-a)"
      },
      {
        "name": "Resolution Capital",
        "v": 4,
        "color": "var(--c-b)"
      },
      {
        "name": "Robeco",
        "v": 2,
        "color": "var(--c-c)"
      }
    ],
    "q2": [
      {
        "name": "BlackRock",
        "v": 40,
        "color": "var(--c-muted)"
      },
      {
        "name": "BetaShares",
        "v": 39,
        "color": "var(--c-us)"
      },
      {
        "name": "Vanguard AU",
        "v": 21,
        "color": "var(--c-c)"
      },
      {
        "name": "UBS",
        "v": 13,
        "color": "var(--c-d)"
      },
      {
        "name": "Perpetual",
        "v": 12,
        "color": "var(--c-b)"
      },
      {
        "name": "Fidelity",
        "v": 10,
        "color": "var(--c-a)"
      },
      {
        "name": "Colonial First State",
        "v": 5,
        "color": "var(--c-a)"
      },
      {
        "name": "Resolution Capital",
        "v": 5,
        "color": "var(--c-b)"
      },
      {
        "name": "Robeco",
        "v": 2,
        "color": "var(--c-c)"
      }
    ]
  }
};
