/* pipeline-data.js - Global Service Request Pipeline (Salesforce), cut 2026-07-31.
   Excludes "Client DDQ" placeholder rows. Used to flag where our targeting data
   (Alphix, email, forms, campaigns) matches a live sales opportunity - a signal
   that marketing is reaching real pipeline. Brand derived from Capability.
   window.MI_PIPELINE, loaded before mi-data.js. */
window.MI_PIPELINE = {
  generatedAt: '2026-07-31',
  source: 'Global Service Request Pipeline (Salesforce)',
  opportunities: [    { name:"Asian Development Bank (ADB)", type:"RFP", brand:"Igneo", capability:"Global Infrastructure", stage:"3-Formalised DD-Long List", active:true },
    { name:"Norges Bank", type:"RFP", brand:"FSSA", capability:"ASEAN", stage:"3-Formalised DD-Long List", active:true },
    { name:"Institutional Money", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"1-Initiated Dialogue", active:true },
    { name:"BFinance (UK)", type:"RFP", brand:"FSSA", capability:"China", stage:"1-Initiated Dialogue", active:true },
    { name:"UNRWA (United Nations Relief and Works Agency)", type:"RFP", brand:"RQI", capability:"Diversified Alpha", stage:"2-Active Engagement", active:true },
    { name:"Secure Spectrum Fondsmæglerselskab", type:"RFP", brand:"Igneo", capability:"NADIF", stage:"2-Active Engagement", active:true },
    { name:"RFPnetworks", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"1-Initiated Dialogue", active:true },
    { name:"BFinance (UK)", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"Lost", active:false },
    { name:"Laborers' and Retirement Board of Employees' Annuity and Benefit Fund of Chicago", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"2-Active Engagement", active:true },
    { name:"Bayerische Versorgungskammer", type:"RFP", brand:"FSSA", capability:"Asian Property Securities", stage:"2-Active Engagement", active:true },
    { name:"IPE Quest", type:"RFP", brand:"RQI", capability:"Value", stage:"1-Initiated Dialogue", active:true },
    { name:"PPCmetrics AG", type:"RFP", brand:"RQI", capability:"Value", stage:"1-Initiated Dialogue", active:true },
    { name:"Social Protection Fund", type:"RFP", brand:"RQI", capability:"", stage:"1-Initiated Dialogue", active:true },
    { name:"Global Fund Search (DACH)", type:"RFP", brand:"FSSA", capability:"Asia Pacific", stage:"1-Initiated Dialogue", active:true },
    { name:"Allied Wealth", type:"RFI", brand:"Igneo", capability:"ADIF", stage:"4-Formalised DD-Short List", active:true },
    { name:"Public Investment Corporation PIC SA", type:"RFP", brand:"Igneo", capability:"Global Infrastructure", stage:"2-Active Engagement", active:true },
    { name:"Evestment", type:"RFP", brand:"FSSA", capability:"China", stage:"1-Initiated Dialogue", active:true },
    { name:"Global Fund Search (DACH)", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"1-Initiated Dialogue", active:true },
    { name:"Morgan Stanley Investment Management", type:"RFI", brand:"Igneo", capability:"NADIF", stage:"7-Account Funded", active:true },
    { name:"Nomura Asset Management Co., Ltd.", type:"RFP", brand:"RQI", capability:"Diversified Alpha", stage:"3-Formalised DD-Long List", active:true },
    { name:"Global Fund Search", type:"RFP", brand:"FSSA", capability:"Asia Pacific", stage:"0-Target Investor – Not Yet Contacted", active:true },
    { name:"Kuwait Investment Authority", type:"RFP", brand:"RQI", capability:"", stage:"1-Initiated Dialogue", active:true },
    { name:"Global Fund Search", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"1-Initiated Dialogue", active:true },
    { name:"Monetary Authority of Singapore", type:"RFP", brand:"FSSA", capability:"ASEAN", stage:"3-Formalised DD-Long List", active:true },
    { name:"Los Angeles City Employees' Retirement System", type:"RFP", brand:"Igneo", capability:"Global Infrastructure", stage:"2-Active Engagement", active:true },
    { name:"Invest RFP", type:"RFP", brand:"RQI", capability:"Value", stage:"1-Initiated Dialogue", active:true },
    { name:"University of Calgary", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"4-Formalised DD-Short List", active:true },
    { name:"Cambridge Retirement System", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"2-Active Engagement", active:true },
    { name:"HSBC Global Asset Management (UK) Ltd", type:"RFI", brand:"Igneo", capability:"EDIF", stage:"Lost", active:false },
    { name:"IPE Quest", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"2-Active Engagement", active:true },
    { name:"BFinance (UK)", type:"RFP", brand:"FSSA", capability:"China", stage:"Lost", active:false },
    { name:"Global Fund Search", type:"RFP", brand:"RQI", capability:"", stage:"0-Target Investor – Not Yet Contacted", active:true },
    { name:"PPCmetrics AG", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"Lost", active:false },
    { name:"PPCmetrics AG", type:"RFP", brand:"Igneo", capability:"EDIF", stage:"Lost", active:false },
    { name:"Team Super", type:"RFP", brand:"RQI", capability:"", stage:"1-Initiated Dialogue", active:true },
    { name:"Mercer Investment Consulting (Montreal, Canada)", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"3-Formalised DD-Long List", active:true },
    { name:"Invest RFP", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"1-Initiated Dialogue", active:true },
    { name:"Invest RFP", type:"RFP", brand:"RQI", capability:"Diversified Alpha", stage:"1-Initiated Dialogue", active:true },
    { name:"RMC Risk Management Consulting GmbH", type:"RFI", brand:"Igneo", capability:"GDIF", stage:"2-Active Engagement", active:true },
    { name:"Nomura Fiduciary Research & Consulting Co., Ltd.", type:"Consultant", brand:"RQI", capability:"Diversified Alpha", stage:"3-Formalised DD-Long List", active:true },
    { name:"Munich Re (Group)", type:"RFP", brand:"RQI", capability:"", stage:"1-Initiated Dialogue", active:true },
    { name:"State Universities Retirement System of Illinois", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"1-Initiated Dialogue", active:true },
    { name:"BFinance (UK)", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"3-Formalised DD-Long List", active:true },
    { name:"RFPnetworks", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"1-Initiated Dialogue", active:true },
    { name:"BFinance (UK)", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"4-Formalised DD-Short List", active:true },
    { name:"Illinois Municipal Retirement Fund", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"3-Formalised DD-Long List", active:true },
    { name:"BFinance (UK)", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"4-Formalised DD-Short List", active:true },
    { name:"Institutional Money", type:"RFP", brand:"FSSA", capability:"India", stage:"Lost", active:false },
    { name:"Illinois Municipal Retirement Fund", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"3-Formalised DD-Long List", active:true },
    { name:"Illinois Municipal Retirement Fund", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"3-Formalised DD-Long List", active:true },
    { name:"HSBC Asset Management Germany", type:"RFP", brand:"Igneo", capability:"EDIF", stage:"7-Account Funded", active:true },
    { name:"HSBC Asset Management Germany", type:"RFP", brand:"Igneo", capability:"EDIF", stage:"7-Account Funded", active:true },
    { name:"Employees Retirement System of Texas", type:"RFP", brand:"RQI", capability:"Value", stage:"1-Initiated Dialogue", active:true },
    { name:"Employees Retirement System of Texas", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"1-Initiated Dialogue", active:true },
    { name:"LGPS Central", type:"RFI", brand:"FSSA", capability:"Global Emerging Markets", stage:"7-Account Funded", active:true },
    { name:"Singapore Tourism Board", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"3-Formalised DD-Long List", active:true },
    { name:"RFPnetworks", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"1-Initiated Dialogue", active:true },
    { name:"RFPnetworks", type:"RFP", brand:"RQI", capability:"Value", stage:"1-Initiated Dialogue", active:true },
    { name:"BlackRock Investment Management (UK)", type:"RFP", brand:"FSSA", capability:"Asia", stage:"3-Formalised DD-Long List", active:true },
    { name:"Oklahoma Tobacco Settlement Endowment Trust", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"Lost", active:false },
    { name:"Team Super", type:"RFP", brand:"RQI", capability:"", stage:"1-Initiated Dialogue", active:true },
    { name:"Alpha Portfolio Advisors GmbH", type:"RFI", brand:"RQI", capability:"Value", stage:"Lost", active:false },
    { name:"Mercer Investments (HK) Limited", type:"RFP", brand:"FSSA", capability:"Global Property Securities", stage:"3-Formalised DD-Long List", active:true },
    { name:"Mercer Investments (HK) Limited", type:"RFP", brand:"FSSA", capability:"Asia", stage:"3-Formalised DD-Long List", active:true },
    { name:"Munich Re (Group)", type:"RFI", brand:"FSI", capability:"Australian Share", stage:"Lost", active:false },
    { name:"The Hong Kong Polytechnic University", type:"RFP", brand:"FSSA", capability:"Asia Pacific", stage:"2-Active Engagement", active:true },
    { name:"Urban Redevelopment Authority (URA)", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"3-Formalised DD-Long List", active:true },
    { name:"Mercer Investment Consulting (Germany)", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"Lost", active:false },
    { name:"Mercer Investment Consulting (Germany)", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"Lost", active:false },
    { name:"c-alm", type:"RFI", brand:"FSSA", capability:"Global Emerging Markets", stage:"Lost", active:false },
    { name:"Aksia", type:"RFI", brand:"Igneo", capability:"GDIF", stage:"2-Active Engagement", active:true },
    { name:"Townsend Group", type:"RFI", brand:"Igneo", capability:"NADIF", stage:"2-Active Engagement", active:true },
    { name:"Townsend Group", type:"RFI", brand:"Igneo", capability:"EDIF", stage:"2-Active Engagement", active:true },
    { name:"Callan Associates (San Francisco)", type:"RFI", brand:"Igneo", capability:"EDIF", stage:"2-Active Engagement", active:true },
    { name:"Townsend Group", type:"RFI", brand:"Igneo", capability:"GDIF", stage:"3-Formalised DD-Long List", active:true },
    { name:"Veska Pensionskasse", type:"RFP", brand:"FSSA", capability:"China", stage:"Lost", active:false },
    { name:"THE BANK OF EAST ASIA, LIMITED", type:"RFP", brand:"FSSA", capability:"Value", stage:"7-Account Funded", active:true },
    { name:"BFinance (Deutschland GmbH)", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"Lost", active:false },
    { name:"Sun Life Hong Kong Limited", type:"RFP", brand:"RQI", capability:"Value", stage:"3-Formalised DD-Long List", active:true },
    { name:"Global Fund Search (DACH)", type:"RFP", brand:"Igneo", capability:"NADIF", stage:"Lost", active:false },
    { name:"Dahab Associates", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"1-Initiated Dialogue", active:true },
    { name:"c-alm", type:"RFP", brand:"FSSA", capability:"China", stage:"Lost", active:false },
    { name:"UAW Retiree Medical Benefits Trust", type:"RFI", brand:"Igneo", capability:"GDIF", stage:"2-Active Engagement", active:true },
    { name:"Nomura Asset Management Co., Ltd.", type:"RFP", brand:"FSSA", capability:"SI - Worldwide Leaders", stage:"Lost", active:false },
    { name:"UAW Retiree Medical Benefits Trust", type:"RFP", brand:"Igneo", capability:"NADIF", stage:"2-Active Engagement", active:true },
    { name:"BFinance (UK)", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"3-Formalised DD-Long List", active:true },
    { name:"Insurance Commission of Western Australia", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"5-Won - Commitment to Proceed", active:true },
    { name:"Complementa", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"2-Active Engagement", active:true },
    { name:"London CIV LGPS", type:"RFP", brand:"FSSA", capability:"Global Emerging Markets", stage:"Lost", active:false },
    { name:"Urban Redevelopment Authority (URA)", type:"RFI", brand:"FSSA", capability:"Global Emerging Markets", stage:"3-Formalised DD-Long List", active:true },
    { name:"Ecofin", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"Lost", active:false },
    { name:"Complementa", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"2-Active Engagement", active:true },
    { name:"JANA Investment Advisers P/L (Australia)", type:"RFP", brand:"", capability:"", stage:"1-Initiated Dialogue", active:true },
    { name:"RMC Risk Management Consulting GmbH", type:"RFP", brand:"", capability:"Senior Direct Lending", stage:"Lost", active:false },
    { name:"Plutos Vermögensverwaltung AG", type:"RFI", brand:"Igneo", capability:"Global Infrastructure", stage:"3-Formalised DD-Long List", active:true },
    { name:"Boston City Retirement System", type:"RFP", brand:"Igneo", capability:"EDIF", stage:"Lost", active:false },
    { name:"Cassa Nazionale di Previdenza ed Assistenza per gli Ingegneri ed Architetti Liberi Professionisti (Inarcassa)", type:"RFI", brand:"Igneo", capability:"NADIF", stage:"1-Initiated Dialogue", active:true },
    { name:"Banca Monte dei Paschi di Siena S.p.A., Fondo Pensione Complementare per i Dipendenti della", type:"RFP", brand:"Igneo", capability:"EDIF", stage:"1-Initiated Dialogue", active:true },
    { name:"CBRE, Inc.", type:"RFP", brand:"Igneo", capability:"NADIF", stage:"2-Active Engagement", active:true },
    { name:"BFinance (UK)", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"Lost", active:false },
    { name:"BFinance (UK)", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"3-Formalised DD-Long List", active:true },
    { name:"Eckler Ltd.", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"3-Formalised DD-Long List", active:true },
    { name:"PPCmetrics AG", type:"RFP", brand:"Igneo", capability:"EDIF", stage:"Lost", active:false },
    { name:"Bristol General Retirement System", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"Lost", active:false },
    { name:"Inter-American Development Bank", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"2-Active Engagement", active:true },
    { name:"Bristol General Retirement System", type:"RFP", brand:"Igneo", capability:"GDIF", stage:"Lost", active:false },
    { name:"Policemen's Annuity and Benefit Fund of Chicago", type:"RFP", brand:"Igneo", capability:"EDIF", stage:"1-Initiated Dialogue", active:true },
    { name:"IPE Quest", type:"RFI", brand:"Igneo", capability:"EDIF", stage:"1-Initiated Dialogue", active:true }
  ]
};

