/* pipeline-data.js - Global Service Request Pipeline (Salesforce), cut 2026-08-03.
   Open + Live opportunities (all stages except Lost), scoped to this brand and to
   the companies that appear in our Alphix data, so every row can surface as a pin.
   status: 'open' (stages 0-4) or 'live' (5-Won / 6-Onboarding / 7-Account Funded).
   window.MI_PIPELINE, loaded before mi-data.js. */
window.MI_PIPELINE = {
  generatedAt: '2026-08-03',
  source: 'Global Service Request Pipeline (Salesforce)',
  opportunities: [
    { name:"(S.E.E) Soka University of America", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"Aberdeen Standard - FSI GLIS", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"AM Life Planning - Claremont", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"Arthur J. Gallagher (Life Solutions) Limited - Brisbane", brand:"FSI", capability:"Concentrated Australian Share", stage:"7-Account Funded", status:"live", active:true },
    { name:"Arts Asset Management GmbH", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Aurora Capital", brand:"FSI", capability:"Responsible Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Best Life Financial Planning", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"Blythesdale Childrens Hospital", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"California State University - FLIIX", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Capital Results", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"Challenger Life", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Chinese University Hong Kong", brand:"FSI", capability:"Asia", stage:"7-Account Funded", status:"live", active:true },
    { name:"Coastal Capital Advice - East Corrimal", brand:"FSI", capability:"Geared Australian Share", stage:"7-Account Funded", status:"live", active:true },
    { name:"Colonial First State (CFS)", brand:"FSI", capability:"Cash and Short Term Investments", stage:"7-Account Funded", status:"live", active:true },
    { name:"Core Fixed Income", brand:"FSI", capability:"US Core / Core+", stage:"7-Account Funded", status:"live", active:true },
    { name:"Core Private Wealth", brand:"FSI", capability:"Responsible Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"D B Financial Services", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"dbfp Deutsche Beratungsgesellschaft für Finanzplanung GmbH", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"DBS Bank (China)", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Deakin University Australia", brand:"FSI", capability:"Small and Mid Caps", stage:"7-Account Funded", status:"live", active:true },
    { name:"Duquesne University", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"Financial Advisers Australia", brand:"FSI", capability:"ex20 - Australian Share", stage:"7-Account Funded", status:"live", active:true },
    { name:"First Sentier Cash Fund", brand:"FSI", capability:"Cash and Short Term Investments", stage:"7-Account Funded", status:"live", active:true },
    { name:"First State Super", brand:"FSI", capability:"Cash and Short Term Investments", stage:"7-Account Funded", status:"live", active:true },
    { name:"Funds SA", brand:"FSI", capability:"Small and Mid Caps", stage:"7-Account Funded", status:"live", active:true },
    { name:"Generation Life Ltd", brand:"FSI", capability:"Global Property Securities", stage:"7-Account Funded", status:"live", active:true },
    { name:"GLIS DWS", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"Hargreaves FSSA All China", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"iFAST Financial Pte Ltd", brand:"FSI", capability:"Responsible Investment", stage:"7-Account Funded", status:"live", active:true },
    { name:"Invesco Pension and Investment Consultants", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"IOOF Funds Management", brand:"FSI", capability:"Cash and Short Term Investments", stage:"7-Account Funded", status:"live", active:true },
    { name:"IOOF Holdings", brand:"FSI", capability:"Equity Income", stage:"7-Account Funded", status:"live", active:true },
    { name:"Isio (London) - formally KPMG LLP", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Kansas University", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"Lake Macquarie Financial Planning", brand:"FSI", capability:"Geared Australian Share", stage:"7-Account Funded", status:"live", active:true },
    { name:"Life Values", brand:"FSI", capability:"Equity Income", stage:"7-Account Funded", status:"live", active:true },
    { name:"Macquarie Financial Services", brand:"FSI", capability:"Growth", stage:"7-Account Funded", status:"live", active:true },
    { name:"Macquarie Group", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"Macquarie Private Wealth - Sydney", brand:"FSI", capability:"Growth", stage:"7-Account Funded", status:"live", active:true },
    { name:"Macquarie Private Wealth - Sydney - 50 Martin Place", brand:"FSI", capability:"ex20 - Australian Share", stage:"7-Account Funded", status:"live", active:true },
    { name:"Macquarie PW", brand:"FSI", capability:"Growth", stage:"7-Account Funded", status:"live", active:true },
    { name:"Mercer", brand:"FSI", capability:"Small and Mid Caps", stage:"7-Account Funded", status:"live", active:true },
    { name:"Mercer - AEQ Small Caps", brand:"FSI", capability:"Small and Mid Caps", stage:"7-Account Funded", status:"live", active:true },
    { name:"Mercer Investments Australia", brand:"FSI", capability:"Concentrated Australian Share", stage:"7-Account Funded", status:"live", active:true },
    { name:"Millennium Wealth - Sydney", brand:"FSI", capability:"ex20 - Australian Share", stage:"7-Account Funded", status:"live", active:true },
    { name:"Ministry of Defence Pension Fund", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Morgan Stanley Smith Barney", brand:"FSI", capability:"Growth", stage:"7-Account Funded", status:"live", active:true },
    { name:"Morgan Stanley Wealth Management", brand:"FSI", capability:"Cash and Short Term Investments", stage:"7-Account Funded", status:"live", active:true },
    { name:"Morrison Pension and Life Assurance Plan-Global Listed Infrastructure", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Mutual Trust", brand:"FSI", capability:"Global Property Securities", stage:"7-Account Funded", status:"live", active:true },
    { name:"Mutual Trust Pty Ltd", brand:"FSI", capability:"Cash and Short Term Investments", stage:"7-Account Funded", status:"live", active:true },
    { name:"New Zealand Fire Service Superannuation Scheme-Global Listed Infrastructure", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Parmenion Capital Partners LLP", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"PFS Financial Group - Royal Park", brand:"FSI", capability:"Cash and Short Term Investments", stage:"7-Account Funded", status:"live", active:true },
    { name:"PGA of America-CA", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"Prime Super - AEQ Core", brand:"FSI", capability:"Growth", stage:"7-Account Funded", status:"live", active:true },
    { name:"Russell", brand:"FSI", capability:"Growth", stage:"7-Account Funded", status:"live", active:true },
    { name:"Russell Investments", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Russell Openworld Plc Global Listed Infrastructure", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Sabal Weath Pty Ltd - East Toowoomba", brand:"FSI", capability:"Equity Income", stage:"7-Account Funded", status:"live", active:true },
    { name:"San Francisco State University Foundation", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"Santander", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"Soka University of America", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"South Nassau Communities Hospital", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"Stride Financial Partners - Hawthorn East", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"University of Adelaide", brand:"FSI", capability:"Cash and Short Term Investments", stage:"7-Account Funded", status:"live", active:true },
    { name:"University of Alaska Foundation (UAF)", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"University of Louisville Foundation", brand:"FSI", capability:"US - Core ++", stage:"7-Account Funded", status:"live", active:true },
    { name:"University of North Carolina (Greenboro)", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"University of Oklahoma Endowment", brand:"FSI", capability:"SI - Global Emerging Markets", stage:"7-Account Funded", status:"live", active:true },
    { name:"Wealth and Co", brand:"FSI", capability:"Global Infrastructure", stage:"7-Account Funded", status:"live", active:true },
    { name:"Wholesale Small Companies Fund ? Core", brand:"FSI", capability:"", stage:"7-Account Funded", status:"live", active:true },
    { name:"BANK OF CHINA (HONG KONG)", brand:"FSI", capability:"Asia", stage:"5-Won - Commitment to Proceed", status:"live", active:true },
    { name:"Bank of East Asia", brand:"FSI", capability:"Global Infrastructure", stage:"5-Won - Commitment to Proceed", status:"live", active:true },
    { name:"China Construction Bank (Asia) Corporation", brand:"FSI", capability:"Global Infrastructure", stage:"5-Won - Commitment to Proceed", status:"live", active:true },
    { name:"Foye Financial Service Pty. Limited - Gundy", brand:"FSI", capability:"Geared Australian Share", stage:"5-Won - Commitment to Proceed", status:"live", active:true },
    { name:"HSBC Bank (Singapore)", brand:"FSI", capability:"ex20 - Australian Share", stage:"5-Won - Commitment to Proceed", status:"live", active:true },
    { name:"Quest Advisory Group", brand:"FSI", capability:"ex20 - Australian Share", stage:"5-Won - Commitment to Proceed", status:"live", active:true },
    { name:"Royal Bank Of Canada (Singapore)", brand:"FSI", capability:"Asia", stage:"5-Won - Commitment to Proceed", status:"live", active:true },
    { name:"Russell Investments (Chicago, USA)", brand:"FSI", capability:"Global Infrastructure", stage:"5-Won - Commitment to Proceed", status:"live", active:true },
    { name:"Russell Investments (Seattle, USA)", brand:"FSI", capability:"Global Infrastructure", stage:"5-Won - Commitment to Proceed", status:"live", active:true },
    { name:"HSBC Private Wealth/Banking", brand:"FSI", capability:"ex20 - Australian Share", stage:"4-Formalised DD-Short List", status:"open", active:true },
    { name:"Mitsui Sumitomo Primary LIfe Insurance", brand:"FSI", capability:"Cash and Short Term Investments", stage:"4-Formalised DD-Short List", status:"open", active:true },
    { name:"Allegra Wealth - First Sentier Cash Fund", brand:"FSI", capability:"Cash and Short Term Investments", stage:"3-Formalised DD-Long List", status:"open", active:true },
    { name:"Mercer Investments (HK) Limited", brand:"FSI", capability:"Global Property Securities", stage:"3-Formalised DD-Long List", status:"open", active:true },
    { name:"Swiss Life Deutschland", brand:"FSI", capability:"Global Infrastructure", stage:"3-Formalised DD-Long List", status:"open", active:true },
    { name:"Tokio Marine Holdings", brand:"FSI", capability:"Cash and Short Term Investments", stage:"3-Formalised DD-Long List", status:"open", active:true },
    { name:"Berenberg GLIS", brand:"FSI", capability:"Global Infrastructure", stage:"2-Active Engagement", status:"open", active:true },
    { name:"CLP Hong Kong Ltd", brand:"FSI", capability:"Asia", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Crown Wealth Group Pty Ltd - Sydney - 338 Pitt Street", brand:"FSI", capability:"Small Cap - Long Short", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Generation Life", brand:"FSI", capability:"Geared Australian Share", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Lufthansa AG", brand:"FSI", capability:"Global Infrastructure", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Mitsubishi UFJ Asset Management Co.,.", brand:"FSI", capability:"Global Infrastructure", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Mitsubishi UFJ Morgan Stanley Securities", brand:"FSI", capability:"Cash and Short Term Investments", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Novia Financial plc", brand:"FSI", capability:"Global Infrastructure", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Prudential Holborn Life Ltd", brand:"FSI", capability:"Global Infrastructure", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Set 4 Life Financial Solutions-Wollongong", brand:"FSI", capability:"Geared Australian Share", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Thai Life", brand:"FSI", capability:"Global Infrastructure", stage:"2-Active Engagement", status:"open", active:true },
    { name:"The Tokio Marine and Fire Insurance Co. (HK) Ltd.", brand:"FSI", capability:"Asia", stage:"2-Active Engagement", status:"open", active:true },
    { name:"Australian Retirement Trust", brand:"FSI", capability:"Growth", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"BNY", brand:"FSI", capability:"American Infrastructure", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"Cork Asset Management Pty Ltd", brand:"FSI", capability:"Cash and Short Term Investments", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"DWS - GLIS", brand:"FSI", capability:"Global Infrastructure", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"Hmh Financial Services - Doncaster East", brand:"FSI", capability:"Geared Australian Share", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"Macquarie Equities - Broadbeach - 19 Victoria Avenue, Broadbeach Mall", brand:"FSI", capability:"Geared Australian Share", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"Mercer Investment Consulting (Dublin)", brand:"FSI", capability:"Global Infrastructure", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"Morgan Stanley", brand:"FSI", capability:"American Infrastructure", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"NorthCorp Wealth Management - Port Macquarie", brand:"FSI", capability:"Small Cap - Long Short", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"Panacea Wealth Management - Macquarie Park", brand:"FSI", capability:"ex20 - Australian Share", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"Partners Capital LLP", brand:"FSI", capability:"Implemented Solution", stage:"1-Initiated Dialogue", status:"open", active:true },
    { name:"University of Guelph", brand:"FSI", capability:"Global Infrastructure", stage:"1-Initiated Dialogue", status:"open", active:true },
  ]
};
